### PR TITLE
Implement encryptor mech

### PR DESCRIPTION
**Pull request by johnjjung**
Our team's built out the corresponding Swift Version of AES Everywhere.

Please let us know what else we need to merge this PR

### CODE REVIEW

**Comment by mervick** [comment]
Thank you!
Please create `swift/README.md` file with instructions

**Comment by mervick** [comment]
Do you agree to publish with MIT license?

**Comment by johnjjung** [comment]
@yYaniv let's put in MIT license and README

**Review by chrisvoronin — CHANGES_REQUESTED** [review]
Encryption does not work the same way as the rest of the library.  It's not clear how to achieve same result.  Also main library uses "SALTED__" as constant, not available here.

Sample of how all other language versions of this would run:
```
let encryptMe = "TEXT"
let password = "PASSWORD"
let encrypted = Aes256.encrypt(encryptMe, password)
let decrypted = Aes256.decrypt(encrypted, password)
```

**Pull request closed without merging**
